version: '3.4'

services:
  aggregationdb:
    container_name: aggregationdb
    environment:
      SA_PASSWORD: "Agr123456"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

  aggregation.api:
    container_name: aggregation.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Aggregation=Data Source=aggregationdb;Initial Catalog=AggregationDb;User Id=sa;Password=Agr123456;"
    depends_on:
      - aggregationdb
    ports:
      - "5001:80"